project:
  type: website
  output-dir: docs
  resources:
    - js/**
    - image/icon/site-icon.png
    - image/icon/apple-touch-icon.png
    - research/file/**

execute:
  freeze: true

website:
  title: "Takaaki Kishida"
  description: "PhD Candidate in Economics"
  site-url: https://takaakikishida.github.io/
  favicon: /image/icon/site-icon.png
  search: false
  navbar:
    background: "white"
    left:
      - href: cv/index.qmd
        text: "cv"
      - href: research/index.qmd
        text: "research"
      - href: notes/index.qmd
        text: "notes"
      - href: fieldworkgallery/index.qmd
        text: "fieldwork gallery"

format:
  html:
    clean-urls: true
    theme:
      - cosmo
      - css/theme.scss
    css: css/styles.css
    include-in-header: includes/favicon.html
    toc: false

lang: en

# editor: visual
