project:
  type: website
  output-dir: docs

website:
  title: "Takaaki Kishida"
  description: "PhD Candidate in Economics"
  site-url: https://takaakikishida.github.io/
  favicon: /image/icon/favicon.ico
  search: false
  navbar:
    background: "white"
    left:
      - href: cv/index.qmd
        text: "cv"
      - href: research/index.qmd
        text: "research"
      - href: note/index.qmd
        text: "note"
      - href: fieldworkgallery/index.qmd
        text: "fieldwork gallery"

format:
  html:
    clean-urls: true
    theme: cosmo
    css: css/styles.css
    toc: false

# editor: visual
