---
title: "CV"
toc: false
body-classes: "page-title-centered section-spacing-wide cv-page"
---

<!-- Feel free to text me if you don't have access to the full text or PDF. -->
\

<!-- ## Note -->

- Before moving to Switzerland in 2022, I completed my studies and worked in the private sector in Japan for about two years.
- A full PDF version of my CV is available upon request.

\


## Short CV (since 2022)

### Education

::: {.cv-container}
<div class="cv-entry">
  <div class="cv-year">2024--present</div>
  <div class="cv-detail">PhD in Economics, University of Geneva</div>
</div>
<div class="cv-entry">
  <div class="cv-year">2022--2024</div>
  <div class="cv-detail">MSc in Economics, University of Lausanne</div>
</div>
:::


### Presentations

::: {.cv-container}
<div class="cv-entry">
  <div class="cv-year">2026</div>
  <div class="cv-detail">7th World Congress of Environmental and Resource Economists (WCERE) (Nova SBE, Portugal)</div>
</div>
<div class="cv-entry">
  <div class="cv-year">2025--26</div>
  <div class="cv-detail">IEE Brown Bag Seminar (U Geneva) * 2</div>
</div>
:::


### TA

::: {.cv-container}
<div class="cv-entry">
  <div class="cv-year">2025--26</div>
  <div class="cv-detail">Environmental Economics and Climate Change (MSc), University of Geneva 
  <br>-- Served as Solo TA
  <br>-- Led tutorials on causal inference, R programming, and an empirical project
  <br>-- Supervised students' replication and extension projects</div>
</div>
:::


### RA

::: {.cv-container}
<div class="cv-entry">
  <div class="cv-year">2025--present</div>
  <div class="cv-detail">For Matthieu Stigler, University of Geneva</div>
</div>
<div class="cv-entry">
  <div class="cv-year">2023--2024</div>
  <div class="cv-detail">For Sébastien Houde, University of Lausanne</div>
</div>
:::


<!-- ### Referee Service -->

<!-- ::: {.cv-container} -->
<!-- <div class="cv-entry"> -->
<!--   <div class="cv-year">2025</div> -->
<!--   <div class="cv-detail">Scientific Reports</div> -->
<!-- </div> -->
<!-- ::: -->

<!-- ### Other Relevant Experience -->

<!-- ::: {.cv-container} -->
<!-- <div class="cv-entry"> -->
<!--   <div class="cv-year">2022--2024</div> -->
<!--   <div class="cv-detail">Graduate Mentee, Mentorship Program, HEC Lausanne, Switzerland</div> -->
<!-- </div> -->
<!-- ::: -->
