---
title: "Tools"
# date: "November 30, 2024"
# lastmod: "November 30, 2024"
# toc: true
# toc-expand: true
# toc-title: "Table of Contents"
# number-sections: true

header-includes: |
    <style>
    h1.title {
      text-align: center;
      margin-top: 15px;
    }
    </style>
---

\

Here are the tools I use for research. 

\

## Productivity

- Project management: [GitHub Projects](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects) (Trello and Notion could be alternatives)
  - I will write a post entirely about GitHub projects
- Task management: GitHub Projects (for project-relevant tasks), [TickTick](https://ticktick.com/?language=en_US) (for personal tasks)
- Note takng: [Notion](https://www.notion.com/) and [Obsidian](https://obsidian.md/)
- Communication: [Discord](https://discord.com/) and [Slack](https://slack.com/)


## Text Editing

- LaTex: Overleaf
- Slide: Beamer (for research presentations) and [Quarto](https://quarto.org/) (for other presentations)
- Reference management: [BibDesk](https://bibdesk.sourceforge.io/)


## PDF Viewers and Editors

- [PDF Expert](https://pdfexpert.com/)
- [Skim](https://skim-app.sourceforge.io/) (for presentations with Mac)
- [GoodNotes](https://www.goodnotes.com/) (for presentations with iPad)


## Hardware

- Laptop: 16-inch MacBook Pro (M3 Pro, 36GB RAM, 2023)
- Keyboard: [HHKB Professional HYBRID Type-S](https://www.hhkeyboard.com/uk/products/hybrid-type-s) 
  - HHKB stands for `Happy Hacking Keyboard`
  - I use it for its unique layout and the almost musical feel of its keystrokes
  - Typing on it is genuinely a pleasure


## Others

- Pen: [Parker Ingenuity 5th](https://www.parkerpen.com/collections/classic/ingenuity/parker-ingenuity-fountain-pen-core-gift-box/SAP_2182013.html) and [Mitsubishi JETSTREAM Prime](https://www.unibrands.co/products/uniball%E2%84%A2-jetstream-3-1-ballpoint-pen?_pos=1&_fid=f80246ec6&_ss=c&variant=43013371822286)
